USE [LessonMonitorDb]

IF (EXISTS (SELECT * 
	FROM INFORMATION_SCHEMA.ROUTINES
	WHERE SPECIFIC_SCHEMA = 'dbo'
	AND ROUTINE_TYPE = 'PROCEDURE'
	AND SPECIFIC_NAME = 'createTimecode'))
 BEGIN
	DROP PROCEDURE [dbo].[createTimecode]
 END
