CREATE DATABASE Homework_3
USE Homework_3

CREATE TABLE Achivment
(
	ID INT PRIMARY KEY NOT NULL,
	Name NVARCHAR(30) NOT NULL
)

CREATE TABLE Student
(
	ID INT PRIMARY KEY NOT NULL,
	Nickname NVARCHAR(20) NOT NULL,
	DateRegistration DATETIME,
	TypeAccount NVARCHAR(10) DEFAULT 'Watcher'
)

CREATE TABLE DateofReceivingAchivment
(
	ID INT PRIMARY KEY NOT NULL,
	AchivmentID INT FOREIGN KEY REFERENCES Achivment(ID),
	StudentID INT FOREIGN KEY REFERENCES Student(ID)
)

ALTER TABLE DateofReceivingAchivment
ADD DateofReceivingAchivment DATETIME NOT NULL

CREATE TABLE Skill
(
	ID INT PRIMARY KEY NOT NULL,
	Name NVARCHAR(20) NOT NULL
)

CREATE TABLE DateofReceivingSkill
(
	ID INT PRIMARY KEY NOT NULL,
	SkillID INT FOREIGN KEY REFERENCES Skill(ID),
	StudentID INT FOREIGN KEY REFERENCES Student(ID)
)

ALTER TABLE DateofReceivingSkill
ADD DateofReceivingSkill DATETIME NOT NULL

CREATE TABLE Lecture
(
	ID INT PRIMARY KEY NOT NULL,
	Name NVARCHAR(20) NOT NULL,
	Date DATETIME NOT NULL
)

CREATE TABLE SkillRelatedLecture
(
	ID INT PRIMARY KEY NOT NULL,
	SkillID INT FOREIGN KEY REFERENCES Skill(ID),
	LectureID INT FOREIGN KEY REFERENCES Lecture(ID)
)