CREATE DATABASE Homework_4
USE Homework_4

--Таймкода, Вопросы, Уроки, Участники
CREATE TABLE Questions
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Topic NVARCHAR(30) NOT NULL,
	Description NVARCHAR(200),
	StudentId INT FOREIGN KEY REFERENCES Students(ID) NOT NULL	
)

CREATE TABLE Students
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nickname NVARCHAR(20) NOT NULL,
	DateRegistration DATETIME,
	TypeAccount NVARCHAR(10) DEFAULT 'Watcher'
)

CREATE TABLE VisitorsLessons
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	StudentID INT FOREIGN KEY REFERENCES Students(ID),
	LessonID INT FOREIGN KEY REFERENCES Lessons(ID)
)
ALTER TABLE VisitorsLessons
ADD CreatedDate DATETIME DEFAULT GETDATE()

CREATE TABLE Lessons
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name NVARCHAR(20) NOT NULL,
	Date DATETIME NOT NULL
)

CREATE TABLE Timecodes
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name NVARCHAR(30) NOT NULL,
	Timecode DATETIME2 NOT NULL,
	LessonId INT FOREIGN KEY REFERENCES Lessons(ID) NOT NULL
)
