CREATE TABLE [dbo].[Questions]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [LessonId] UNIQUEIDENTIFIER NOT NULL, 
    [MemberId] UNIQUEIDENTIFIER NOT NULL, 
    [Body] NVARCHAR(MAX) NULL, 
    [Status] BIT NULL DEFAULT 0
)
