CREATE DATABASE LessonMonitorDb

USE LessonMonitorDb


CREATE TABLE Questions
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name NVARCHAR(30) NOT NULL,
	Description NVARCHAR(200)
)

CREATE TABLE Students
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nickname NVARCHAR(20) NOT NULL,
	DateRegistration DATETIME,
	TypeAccount NVARCHAR(10) DEFAULT 'Watcher'
)

CREATE TABLE QuestionsStudents
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	StudentID INT FOREIGN KEY REFERENCES Students(ID),
	QuestionID INT FOREIGN KEY REFERENCES Questions(ID)
)

CREATE TABLE Lessons
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name NVARCHAR(20) NOT NULL,
	Date DATETIME NOT NULL
)

CREATE TABLE VisitorsLessons
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	StudentID INT FOREIGN KEY REFERENCES Students(ID),
	LessonID INT FOREIGN KEY REFERENCES Lessons(ID)
)


CREATE TABLE Timecodes
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name NVARCHAR(30) NOT NULL,
	Timecode DATETIME
)

CREATE TABLE LessonsTimecodes
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	TimecodesID INT FOREIGN KEY REFERENCES Timecodes(ID),
	LessonID INT FOREIGN KEY REFERENCES Lessons(ID)
)

